version: '3.9'

services:
  starfish-controller:
    container_name: starfish-controller
    build:
      context: .
    image: starfish-controller
    depends_on:
      - controller-scheduler
      - controller-run-worker
      - controller-processor-worker
      - redis
    ports:
      - '8001:8000'
    env_file:
      - .env
    command: bash -c "cron && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - artifacts:/starfish-controller/local
      - ./starfish:/app/starfish
      - ./manage.py:/app/manage.py

  controller-scheduler:
    container_name: starfish-controller-scheduler
    build:
      context: .
    image: starfish-controller
    depends_on:
      - redis
    env_file:
      - .env
    entrypoint: [ "celery", "-A", "starfish", "beat", "-l", "DEBUG" ]
    volumes:
      - artifacts:/starfish-controller/local
      - ./starfish:/app/starfish

  controller-run-worker:
    container_name: starfish-controller-run-worker
    build:
      context: .
    image: starfish-controller
    depends_on:
      - redis
    env_file:
      - .env
    entrypoint: [ "celery", "-A", "starfish", "worker", "-l", "DEBUG", "-Q", "starfish.run" ]
    volumes:
      - artifacts:/starfish-controller/local
      - ./starfish:/app/starfish

  controller-processor-worker:
    container_name: starfish-controller-processor-worker
    build:
      context: .
    image: starfish-controller
    depends_on:
      - redis
    env_file:
      - .env
    entrypoint: [ "celery", "-A", "starfish", "worker", "-l", "DEBUG", "--concurrency=1", "-Q", "starfish.processor" ]
    volumes:
      - artifacts:/starfish-controller/local
      - ./starfish:/app/starfish


  redis:
    image: redis:5.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/opt/redis/data

volumes:
  artifacts: {}
  redis_data: {}

networks:
  default:
    name: starfish-network
